dict = [
    {
        "row_number": 0,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "private", 'smoke-mc'],
        "cloudprofile": "Multinic Tier Deployment on Private Cloud",
        "deliveryprofile": "Round Robin",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "sdnprofile": "None",
        "slaprofile": "High CPU",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 1,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Bursting to Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 2,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Bursting to EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 3,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Balancing with Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 4,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 5,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 6,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Balancing with Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU",
        "run_tests": ["ScaleupAppNoSLA"]
    },
    {
        "row_number": 7,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "private", 'smoke-mc'],
        "cloudprofile": "Multinic Tier Deployment on Private Cloud",
        "deliveryprofile": "Round Robin",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "sdnprofile": "None",
        "slaprofile": "High CPU",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 8,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Bursting to Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "Real Multi SLA",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 9,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Bursting to EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "Real Multi SLA",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 10,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Balancing with Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "Real Multi SLA",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 11,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "Real Multi SLA",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 12,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "Real Multi SLA",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 13,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Balancing with Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "Real Multi SLA",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 14,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Bursting to Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Response Time",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 15,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Bursting to EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Response Time",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 16,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs2"],
        "cloudprofile": "Multinic Cloud Balancing with Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Response Time",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 17,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Response Time",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 18,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Response Time",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 19,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Balancing with Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Response Time",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 20,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Bursting to Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput WAF",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 21,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Bursting to EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput WAF",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 22,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Balancing with Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput WAF",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 23,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput WAF",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 24,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput WAF",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 25,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Balancing with Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput WAF",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 26,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Bursting to Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 27,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Bursting to EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 28,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Balancing with Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 29,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 30,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 31,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Balancing with Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Throughput",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 32,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Bursting to Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU and Low Memory",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 33,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Bursting to EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU and Low Memory",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 34,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Balancing with Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU and Low Memory",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 35,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU and Low Memory",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 36,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU and Low Memory",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 37,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic" "azure", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU and Low Memory",
        "run_tests": ['cloud_multinic']
    },
    {
        "row_number": 38,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Bursting to Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Connections per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 39,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Bursting to EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Connections per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 40,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Balancing with Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Connections per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 41,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Connections per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 42,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Connections per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 43,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Balancing with Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High Connections per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 44,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Bursting to Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High SSL transactions per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 45,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Bursting to EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High SSL transactions per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 46,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "rs"],
        "cloudprofile": "Multinic Cloud Balancing with Rackspace",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High SSL transactions per second",
        "run_tests": ['cloud_multinic']
    },
    {
        "row_number": 47,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic", "ec2", 'smoke-mc'],
        "cloudprofile": "Multinic Cloud Balancing with EC2",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High SSL transactions per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 48,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High SSL transactions per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 49,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Balancing with Azure",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High SSL transactions per second",
        "run_tests": ['cloud_multinic', 'Web Server']
    },

    {
        "row_number": 50,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Balancing with GCE",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU and Low Memory",
        "run_tests": ['cloud_multinic', 'Web Server']
    },
    {
        "row_number": 51,
        "description": "multiniccloudprofiles",
        "test_flag": ["multinic"],
        "cloudprofile": "Multinic Cloud Bursting to GCE",
        "deliveryprofile": "Round Robin",
        "sdnprofile": "None",
        "securityprofile": "WAF Disabled , DPI Disabled",
        "serverprofile": "MultinicServer",
        "slaprofile": "High CPU and Low Memory",
        "run_tests": ['cloud_multinic', 'Web Server']
    }


]
